
replicaCount: 2

image:
  repository: 432837989123.dkr.ecr.eu-central-1.amazonaws.com/cloud-native-app
  tag: "0ee1140ebc7277708e0009d4c4b1d56db8a4e39f"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: nginx
  host: cloud-native.local

app:
  environment: kubernetes
  logLevel: INFO

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
