apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/balachmir-cp-2077/cloud-native-devops-platform.git
    targetRevision: master
    path: helm/cloud-native-app

  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-native-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
