apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-native-app.fullname" . }}-secret
  labels:
    {{- include "cloud-native-app.labels" . | nindent 4 }}

type: Opaque

stringData:
  DEMO_API_KEY: "local-development-only"